In [45]:
import numpy as np
N = input('Введите количествоэлементов')
np.arange(0, int(N))

Введите количествоэлементов1


array([0])

In [37]:
N = input('Введите количество элементов')
a = np.arange(  int(N),0, -1,) 
print ( np.diag(a, k = 0 ))

print(sum(a))

Введите количество элементов10
[[10  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  1]]
55


In [48]:
a = np.array([[1, 4, 1], [1, 3, 0], [0 , 5, 4]])
b = np.array([4, 12, -3])
print(np.linalg.solve(a,b))
np.allclose( np.dot(a, np.linalg.solve(a, b)), b )

[-75.  29. -37.]


True