In [14]:
import numpy as np
N = input('Введите количествоэлементов')
np.arange(int(N)-1, -1 , -1)

Введите количествоэлементов9


array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [5]:
N = input('Введите количество элементов')
a = np.arange(  int(N),0, -1,) 
print ( np.diag(a, k = 0 ))

print(sum(a))

Введите количество элементов3
[[3 0 0]
 [0 2 0]
 [0 0 1]]
6


In [4]:
a = np.array([[4, 2, 1], [1, 3, 0], [0 , 5, 4]])
b = np.array([4, 12, -3])
print(np.linalg.solve(a,b))
np.allclose( np.dot(a, np.linalg.solve(a, b)), b )

[ 0.46666667  3.84444444 -5.55555556]


True